import type { UsbDmxConfig, SerialPortInfo } from '../shared/types'

/**
 * USB DMX Output - supports multiple cheap USB-DMX adapters:
 *
 * 1. ENTTEC Open DMX USB / Eurolite / clones (FTDI-based, ~30EUR)
 *    - Simple serial at 250kbaud, sends raw DMX frames
 *    - BREAK generated by switching baud to 76800 momentarily
 *    - No feedback, cheapest option
 *
 * 2. ENTTEC DMX USB Pro (~150EUR)
 *    - Uses ENTTEC Pro protocol with message framing
 *    - More reliable, has RDM support
 *    - USB serial at 57600 baud, internal chip generates 250kbaud DMX
 *
 * Note: Eurolite USB-DMX512 "Pro" is FTDI-based (Open DMX protocol),
 * NOT an ENTTEC Pro clone. The "Pro" just means better build quality.
 */

interface UsbDmxInstance {
  config: UsbDmxConfig
  port: any // SerialPort instance
  connected: boolean
  buffer: Buffer
  sending: boolean // guard against concurrent writes
}

export class UsbDmxOutput {
  private instances: Map<number, UsbDmxInstance> = new Map()
  private SerialPort: any = null
  private available = false

  constructor() {
    try {
      const sp = require('serialport')
      this.SerialPort = sp.SerialPort
      this.available = true
      console.log('[USB-DMX] serialport module loaded successfully')
    } catch (e) {
      console.warn('[USB-DMX] serialport not available:', (e as Error).message)
      this.available = false
    }
  }

  /**
   * Scan for available serial ports (USB DMX adapters)
   */
  async scanPorts(): Promise<SerialPortInfo[]> {
    if (!this.available) return []
    try {
      const { SerialPort } = require('serialport')
      const ports = await SerialPort.list()
      console.log(`[USB-DMX] Scan found ${ports.length} port(s)`)
      return ports.map((p: any) => {
        console.log(`[USB-DMX]   ${p.path} — ${p.manufacturer || 'unknown'} VID:${p.vendorId || '?'} PID:${p.productId || '?'} SN:${p.serialNumber || '?'}`)
        return {
          path: p.path,
          manufacturer: p.manufacturer || undefined,
          serialNumber: p.serialNumber || undefined,
          vendorId: p.vendorId || undefined,
          productId: p.productId || undefined,
          friendlyName: p.friendlyName || p.pnpId || undefined
        }
      })
    } catch (e) {
      console.error('[USB-DMX] Failed to scan ports:', e)
      return []
    }
  }

  /**
   * Configure USB DMX outputs
   */
  async configure(configs: UsbDmxConfig[]): Promise<void> {
    console.log(`[USB-DMX] Configuring ${configs.length} output(s)...`)
    // Close existing connections
    await this.destroyAll()

    if (!this.available) {
      console.warn('[USB-DMX] serialport module not available — cannot configure')
      return
    }

    for (const config of configs) {
      try {
        console.log(`[USB-DMX] Opening ${config.driver} on ${config.portPath} (universe ${config.universe})...`)
        const instance = await this.openPort(config)
        if (instance) {
          this.instances.set(config.universe, instance)
          console.log(`[USB-DMX] ✓ ${config.driver} on ${config.portPath} ready (universe ${config.universe})`)
        }
      } catch (e) {
        console.error(`[USB-DMX] ✗ Failed to open ${config.driver} on ${config.portPath}:`, e)
      }
    }
    console.log(`[USB-DMX] Configuration complete: ${this.instances.size} output(s) active`)
  }

  /**
   * Determine which protocol to use based on driver type.
   * ENTTEC Pro protocol: message framing at 57600 baud, microcontroller handles DMX BREAK.
   * Open DMX protocol: raw frames at 250kbaud, host must generate BREAK via serial.
   *
   * Eurolite USB-DMX512 Pro has an internal microcontroller → uses Pro protocol.
   */
  private isProProtocol(driver: string): boolean {
    return driver === 'enttec-pro' || driver === 'eurolite-pro'
  }

  private async openPort(config: UsbDmxConfig): Promise<UsbDmxInstance | null> {
    const { SerialPort } = require('serialport')

    if (this.isProProtocol(config.driver)) {
      return this.openEnttecPro(SerialPort, config)
    }

    // All other drivers use FTDI-based Open DMX protocol
    return this.openEnttecOpen(SerialPort, config)
  }

  /**
   * ENTTEC Open DMX USB - simple FTDI serial at 250kbaud
   * Sends raw DMX512 frames: BREAK + MAB + START_CODE + 512 bytes
   */
  private async openEnttecOpen(SP: any, config: UsbDmxConfig): Promise<UsbDmxInstance> {
    const port = new SP({
      path: config.portPath,
      baudRate: 250000,
      dataBits: 8,
      stopBits: 2,
      parity: 'none',
      autoOpen: false
    })

    return new Promise((resolve, reject) => {
      port.open((err: Error | null) => {
        if (err) {
          reject(err)
          return
        }
        console.log(`[USB-DMX] Open DMX connected on ${config.portPath} (250kbaud, 8N2)`)
        const buffer = Buffer.alloc(513) // Start code (0x00) + 512 channels
        buffer[0] = 0x00 // DMX start code
        resolve({
          config,
          port,
          connected: true,
          buffer,
          sending: false
        })
      })
    })
  }

  /**
   * ENTTEC DMX USB Pro - uses message protocol
   * Frame format: 0x7E [label] [length_lsb] [length_msb] [data...] 0xE7
   */
  private async openEnttecPro(SP: any, config: UsbDmxConfig): Promise<UsbDmxInstance> {
    const port = new SP({
      path: config.portPath,
      baudRate: 57600,
      dataBits: 8,
      stopBits: 1,
      parity: 'none',
      autoOpen: false
    })

    return new Promise((resolve, reject) => {
      port.open((err: Error | null) => {
        if (err) {
          reject(err)
          return
        }
        console.log(`[USB-DMX] ENTTEC Pro connected on ${config.portPath} (57600 baud)`)
        // Pro frame: header(1) + label(1) + length(2) + start_code(1) + 512ch + footer(1) = 518
        const buffer = Buffer.alloc(518)
        resolve({
          config,
          port,
          connected: true,
          buffer,
          sending: false
        })
      })
    })
  }

  private sendCount = 0

  /**
   * Send DMX data to all connected USB adapters
   */
  send(universes: Uint8Array[]): void {
    for (const [universeIdx, instance] of this.instances) {
      if (!instance.connected || universeIdx >= universes.length) continue
      // Skip if previous frame is still being sent
      if (instance.sending) return

      const data = universes[universeIdx]

      // Diagnostic: log every 200th frame + any non-zero channel 40 (Fuzzix at addr 041)
      this.sendCount++
      if (this.sendCount % 200 === 1) {
        const nonZero = Array.from(data).filter(v => v > 0).length
        console.log(`[USB-DMX] Frame #${this.sendCount} → ${instance.config.driver} U${universeIdx} | ${nonZero} non-zero ch | ch40-47: [${data[40]},${data[41]},${data[42]},${data[43]},${data[44]},${data[45]},${data[46]},${data[47]}] | connected=${instance.connected} sending=${instance.sending}`)
      }

      if (this.isProProtocol(instance.config.driver)) {
        this.sendEnttecPro(instance, data)
      } else {
        this.sendOpenDmx(instance, data)
      }
    }
  }

  /**
   * Send raw DMX frame (Open DMX / FTDI style)
   * Uses the serial BREAK signal (port.set brk) for proper DMX512 BREAK timing.
   * Frame: BREAK (≥88µs) + MAB (≥8µs) + START_CODE(0x00) + 512 channel bytes
   */
  private sendOpenDmx(instance: UsbDmxInstance, data: Uint8Array): void {
    try {
      if (!instance.port || !instance.port.isOpen) {
        instance.connected = false
        return
      }

      instance.sending = true

      // Copy channel data after start code
      for (let i = 0; i < 512; i++) {
        instance.buffer[i + 1] = data[i]
      }

      // 1. Assert BREAK on the DMX line
      instance.port.set({ brk: true, rts: false }, (err: Error | null) => {
        if (err || !instance.connected) {
          console.error(`[USB-DMX] BREAK set error:`, err?.message)
          instance.sending = false
          return
        }
        // 2. Hold BREAK for ~1ms (DMX spec requires ≥88µs)
        setTimeout(() => {
          // 3. Release BREAK (start Mark After Break)
          instance.port.set({ brk: false, rts: false }, (err2: Error | null) => {
            if (err2 || !instance.connected) {
              console.error(`[USB-DMX] BREAK release error:`, err2?.message)
              instance.sending = false
              return
            }
            // 4. Send DMX frame (start code + 512 channels)
            instance.port.write(instance.buffer, (err3: Error | null) => {
              if (err3) {
                console.error(`[USB-DMX] Write error:`, err3.message)
                instance.connected = false
              }
              instance.port.drain(() => {
                instance.sending = false
              })
            })
          })
        }, 1)
      })
    } catch (e) {
      console.error(`[USB-DMX] Send error (${instance.config.driver}):`, (e as Error).message)
      instance.connected = false
      instance.sending = false
    }
  }

  /**
   * Send ENTTEC Pro message frame
   * Label 6 = "Send DMX Packet"
   * The Pro hardware handles BREAK/MAB timing internally.
   */
  private sendEnttecPro(instance: UsbDmxInstance, data: Uint8Array): void {
    try {
      if (!instance.port || !instance.port.isOpen) {
        instance.connected = false
        return
      }

      instance.sending = true

      const dataLength = 513 // start code + 512 channels
      const buf = instance.buffer

      buf[0] = 0x7E        // Start delimiter
      buf[1] = 6            // Label: Send DMX Packet
      buf[2] = dataLength & 0xFF        // Length LSB
      buf[3] = (dataLength >> 8) & 0xFF // Length MSB
      buf[4] = 0x00         // DMX start code

      // Copy channel data
      for (let i = 0; i < 512; i++) {
        buf[i + 5] = data[i]
      }

      buf[517] = 0xE7       // End delimiter

      instance.port.write(buf, (err: Error | null) => {
        if (err) {
          console.error(`[USB-DMX] Pro write error on ${instance.config.portPath}:`, err.message)
          instance.connected = false
        }
        instance.port.drain(() => {
          instance.sending = false
        })
      })
    } catch (e) {
      console.error(`[USB-DMX] Pro send error (${instance.config.driver}):`, (e as Error).message)
      instance.connected = false
      instance.sending = false
    }
  }

  /**
   * Get status of all USB DMX outputs
   */
  getStatus(): { available: boolean; outputs: { universe: number; driver: string; port: string; connected: boolean }[] } {
    return {
      available: this.available,
      outputs: Array.from(this.instances.entries()).map(([universe, inst]) => ({
        universe,
        driver: inst.config.driver,
        port: inst.config.portPath,
        connected: inst.connected
      }))
    }
  }

  /**
   * Close all ports
   */
  async destroyAll(): Promise<void> {
    for (const [, instance] of this.instances) {
      instance.connected = false // Stop sends immediately
      try {
        if (instance.port && instance.port.isOpen) {
          await new Promise<void>((resolve) => {
            instance.port.close(() => resolve())
          })
        }
      } catch (e) {
        // Ignore close errors
      }
    }
    this.instances.clear()
  }

  isAvailable(): boolean {
    return this.available
  }
}
